name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: instal dep
      run: npm install
    - name: build website
      run: npm run build-only
    - name: Build the Docker image
      run: docker build . --tag portfolio:latest
